////2 Try reassigning a  const  variable and catch the error using  try...catch . Print the error message
const name  = 'Alen'
try{
 name = 'Akshara'
}
catch(error){
  console.log(error)
}